config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root 'static_pages#index'
    resources :products
    resources :categories
    resources :tables
    resources :locations
    resources :reports, only: [:index, :show]
    resources :week_reports, only: [:index]
    resources :month_reports, only: [:index]
    resources :year_reports, only: [:index]
    namespace :ajax do
      resources :products_orders
      resources :orders_reports
      resources :week_reports
      resources :area_locations
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord

  has_many :addresses, dependent: :destroy
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_action :load_location, only: %i(destroy edit show update)

  def index

    @search = Location.search params[:q]
    @search.sorts  = "created_at desc" if @search.sorts.empty?
    @locations = @search.result.page(params[:page]).per_page 10

  end

  def show

  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new location_params
    if @location.save
      flash[:success] = "Bạn đả tạo thành công"
      create_location_address @location.id
      redirect_to admin_locations_path
    else

      flash[:danger] = "Bạn đả tạo không thành công"
      render :new
    end
  end

  def destroy
    if @location.destroy
      flash[:success] = "Chúc mừng bạn đả xóa thành công."
    else
      flash[:danger] = "Xin lỗi ! Bạn đã xóa không thành công, xin thử lại."
    end
    redirect_to admin_locations_path
  end

  def update
    if @location.update_attributes location_params
      flash[:success] = "Chúc mừng bạn đả cập nhật thành công."
      redirect_to admin_locations_path
    else

      flash[:danger] = "Xin lỗi ! Bạn đã cập nhật không thành công."
      render :edit
    end
  end

  def edit

  end

  private

  def location_params
    current_params = params.require(:location).permit(:name, :description, :row, :column)
  end

  def load_location
    @location = Location.find_by id: params[:id]
  end

  def create_location_address location_id
    (1..params[:location][:row].to_i).each do |row|
      Address.create!(location_id: location_id, row_index: row, col_index: params[:location][:column])
    end
  end
end

app/views/admin/locations/_location.html.erb
<tr>
  <td><%= location.name %></td>
  <td><%= location.description %></td>
  <td><%= location.row %></td>
  <td><%= location.column %></td>
  <td class="tac-vu">
    <%= link_to admin_location_path(location), class: "button-show", data: {turbolinks: false} do %>
          <span class="button-inner">
            <button class="btn button button-show-small">
              <span class="text">Chi Tiết</span>
            </button>
          </span>
    <% end %>
    <%= link_to edit_admin_location_path(location), class: "button-edit" do %>
          <span class="button-inner">
            <button class="btn button button-edit-small">
              <span class="text">Chỉnh Sửa</span>
            </button>
          </span>
    <% end %>
    <%= link_to admin_location_path(location),method: :delete,
      data: {confirm: "Bạn chắc chắn muốn xóa"}, class: "button-delete" do %>
          <span class="button-inner">
            <button class="btn button button-delete-small">
              <span class="text">Xóa</span>
            </button>
          </span>
    <% end %>
  </td>
</tr>

app/views/admin/locations/_location_form.html.erb
<%= form_for [:admin, location], html: {class: "form-horizontal"} do |f| %>
  <div class="box-body">

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Tên Mặt Bằng</label>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Nhập Tên Mặt Bằng" %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Chú Thích</label>
      <div class="col-sm-8">
        <%= f.text_field :description, class: "form-control", placeholder: "Nhập Chú Thích" %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Ngang x 1/2 mét</label>
      <div class="col-sm-8">
        <%= f.number_field :row, class: "form-control", placeholder: "Diện Tích Bề Ngang" %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Dọc x 1/2 mét</label>
      <div class="col-sm-8">
        <%= f.number_field :column, class: "form-control", placeholder: "Diện Tích Bề Dọc" %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

  </div>
  <div class="box-footer">
    <%= link_to "Trở Về", admin_locations_path, class: "btn btn-default btn-warning" %>
    <% if location.persisted?%>
      <%= f.submit "Chỉnh Sửa", class: "btn btn-info pull-right load-alert" %>
    <% else %>
      <%= f.submit "Tạo Mới", class: "btn btn-info pull-right load-alert" %>
    <% end %>
  </div>
<% end %>

app/views/admin/locations/_location_form.js.erb
"use strict";

//Tạo vùng chứa cho các phương pháp bên dưới
var redips = {};


// REDIPS.table khởi tạo
redips.init = function () {

	// Xác định biết tham chiếu cho REDIPS.table
  var rd = REDIPS.drag;
	// Xác định biết tham chiếu cho REDIPS.table
	var rt = REDIPS.table;
	// Kích hoạt onmousedown cho bảng với id="mainTable"
	rt.onmousedown('mainTable', true);

	// rt.cell_index(true); //Hiển thị tọa độ
	// màu khi click vào từng ô
	rt.color.cell = '#9BB3DA';
  rd.init();
};


// function merges table cells
redips.merge = function () {
	// first merge cells horizontally and leave cells marked
	REDIPS.table.merge('h', false);
	// and then merge cells vertically and clear cells (second parameter is true by default)
	REDIPS.table.merge('v');
};


// function splits table cells if colspan/rowspan is greater then 1
// mode is 'h' or 'v' (cells should be marked before)
redips.split = function (mode) {
	REDIPS.table.split(mode);
};


// insert/delete table row
redips.row = function (type) {
	REDIPS.table.row('mainTable', type);
  var location_id = $("#location_info").data("locationid");
  var url = "<%= admin_ajax_area_locations_path %>"
  $.ajax({
    type: "GET",
    url: url,
    dataType: "script",
    data: {
      action_name: "row",
      action_type: type,
      location_id: location_id
    }
  });
};


// insert/delete table column
redips.column = function (type) {
	REDIPS.table.column('mainTable', type);
  var location_id = $("#location_info").data("locationid");
  var url = "<%= admin_ajax_area_locations_path %>"
  $.ajax({
    type: "GET",
    url: url,
    dataType: "script",
    data: {
      action_name: "column",
      action_type: type,
      location_id: location_id
    }
  });
};


// add onload event listener
if (window.addEventListener) {
	window.addEventListener('load', redips.init, false);
}
else if (window.attachEvent) {
	window.attachEvent('onload', redips.init);
}

app/views/admin/locations/edit.html.erb
<section class="content-header menu-header-button">
  <%= link_to new_admin_location_path, class: "btn icon-btn btn-danger" do %>
    <span class="glyphicon btn-glyphicon glyphicon-plus img-circle text-danger"></span>
    Thêm Mới
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t ".title" %></h3>
        </div>
        <%= render "location_form", location: @location %>
      </div>
    </div>
  </div>
</section>

app/views/admin/locations/index.html.erb
<section class="content-header menu-header-button">
  <%= link_to new_admin_location_path, class: "btn icon-btn btn-danger" do %>
    <span class="glyphicon btn-glyphicon glyphicon-plus img-circle text-danger"></span>
    Thêm Mới
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Thiết Lập Số Mặt Bằng</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool btn-filter">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
        <div class="box-body table-responsive no-padding min-height-600">
          <%= render "location_form_search", search: @search, form: @form %>
          <div class="notices_result">
            <% if @locations.any? %>
              <table class="table table-hover table-striped">
                <thead class="thead-inverse">
                  <th><%= sort_link @search, :name, "Tên Mặt Bằng" %></th>
                  <th><%= sort_link @search, :description, "Ghi Chú" %></th>
                  <th><%= sort_link @search, :row, "Hàng (Chỉ Số x 1/2 mét)" %></th>
                  <th><%= sort_link @search, :column, "Cột (Chỉ Số x 1/2 mét)" %></th>
                  <th class="tac-vu">Tác Vụ</th>
                </thead>
                <tbody>
                  <%= render @locations %>
                </tbody>
              </table>
              <div class="pagination_center">
                <%= will_paginate @locations %>
              </div>
            <% else %>
              <h3 class="text-center">Không có mặt bằng nào.</h3>
              <div class="col-xs-12 text-center margin-bottom-30">
                <%= link_to "Trở lại", admin_locations_path, class: "btn btn-default bg-red" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/locations/new.html.erb
<section class="content-header menu-header-button">
  <%= link_to admin_locations_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Tạo Mới Tầng Lầu</h3>
        </div>
        <%= render "location_form", location: @location %>
      </div>
    </div>
  </div>
</section>

app/views/admin/locations/show.html.erb
<section class="content-header menu-header-button">
  <%= link_to new_admin_location_path, class: "btn icon-btn btn-danger" do %>
    <span class="glyphicon btn-glyphicon glyphicon-plus img-circle text-danger"></span>
    Thêm Mới
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>


<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Thay Đổi Vị Trí Và Cấu Trúc Khuôn Viên</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool btn-filter">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
        <div class="box-header with-border" style=" text-align: center; ">
          <%= link_to "javascript:void(0);", class: "button-show", onclick: "redips.merge()" do %>
                <span class="button-inner">
                  <button class="btn button button-show-small">
                    <span class="text">Gộp Hàng Hoặc Cột</span>
                  </button>
                </span>
          <% end %>
          <%= link_to "javascript:void(0);", class: "button-show", onclick: "redips.split('h')" do %>
                <span class="button-inner">
                  <button class="btn button button-show-small">
                    <span class="text">Chia Theo Hàng Ngang</span>
                  </button>
                </span>
          <% end %>
          <%= link_to "javascript:void(0);", class: "button-show", onclick: "redips.split('v')" do %>
                <span class="button-inner">
                  <button class="btn button button-show-small">
                    <span class="text">Chia Theo Hàng Dọc</span>
                  </button>
                </span>
          <% end %>

          <%= link_to "javascript:void(0);", class: "button-edit", onclick: "redips.row('insert')" do %>
                <span class="button-inner">
                  <button class="btn button button-edit-small">
                    <span class="text">Thêm Hàng</span>
                  </button>
                </span>
          <% end %>

          <%= link_to "javascript:void(0);", class: "button-delete", onclick: "redips.row('delete')" do %>
                <span class="button-inner">
                  <button class="btn button button-delete-small">
                    <span class="text">Xóa Hàng</span>
                  </button>
                </span>
          <% end %>

          <%= link_to "javascript:void(0);", class: "button-edit", onclick: "redips.column('insert')" do %>
                <span class="button-inner">
                  <button class="btn button button-edit-small">
                    <span class="text">Thêm Cột</span>
                  </button>
                </span>
          <% end %>

          <%= link_to "javascript:void(0);", class: "button-delete", onclick: "redips.column('delete')" do %>
                <span class="button-inner">
                  <button class="btn button button-delete-small">
                    <span class="text">Xóa Cột</span>
                  </button>
                </span>
          <% end %>
        </div>
        <div class="box-body table-responsive no-padding min-height-600">
                <!-- container -->
                <div id="redips-drag" class="table-responsive">
                  <!-- table1 -->
                  <table id="table1">
                      <colgroup>
                          <col width="1"/> <!-- needed to have both tables nicely aligned -->
                          <col width="100"/>
                          <col width="100"/>
                          <col width="100"/>
                      </colgroup>
                      <tbody>

                          <!-- clone 2 elements + trash -->
                          <tr>
                              <!-- <td class="redips-mark"></td> -->
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/computer_1.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/tv.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>

                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/tr.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/tree.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>

                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/table_off.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/table-bar.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/toilet1.png", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/toilet2.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/toilet3.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/toilet4.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/thang1.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/thang2.svg", height: "70px", width: "70px" %>
                                </div>
                              </td>
                              <td class="redips-single">
                                <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                  <%= image_tag "icon/thang3.png", height: "70px", width: "70px" %>
                                </div>
                              </td>

                              <td class="redips-trash">Xóa</td>
                           </tr>
                           <tr>

                             <td class="redips-single">
                               <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                 <%= image_tag "icon/wall1.jpg", height: "70px", width: "70px" %>
                               </div>
                             </td>
                             <td class="redips-single">
                               <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                 <%= image_tag "icon/wall2.jpg", height: "70px", width: "70px" %>
                               </div>
                             </td>
                             <td class="redips-single">
                               <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                 <%= image_tag "icon/wall_detail.svg", height: "70px", width: "70px" %>
                               </div>
                             </td>
                             <td class="redips-single">
                               <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                 <%= image_tag "icon/wall_row.svg", height: "70px", width: "70px" %>
                               </div>
                             </td>
                             <td class="redips-single">
                               <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                 <%= image_tag "icon/wall_yallow.svg", height: "70px", width: "70px" %>
                               </div>
                             </td>
                             <td class="redips-single">
                               <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                 <%= image_tag "icon/door1.svg", height: "70px", width: "70px" %>
                               </div>
                             </td>
                             <td class="redips-single">
                               <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                 <%= image_tag "icon/door2.svg", height: "70px", width: "70px" %>
                               </div>
                             </td>
                             <td class="redips-single">
                               <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                 <%= image_tag "icon/door3.svg", height: "70px", width: "70px" %>
                               </div>
                             </td>
                             <td class="redips-single">
                               <div class="redips-drag redips-clone border-hidden" style=" height: 70px; width: 70px; ">
                                 <%= image_tag "icon/door4.svg", height: "70px", width: "70px" %>
                               </div>
                             </td>
                           </tr>
                         </tbody>
                       </table>

                       <h3 style="text-align: center;" id="location_info" data-locationid="<%= @location.id %>"><%= @location.name %></h3>

                  <!-- main table -->
                  <table id="mainTable">
                    <tbody>
                      <% (1..@location.row).each do |row| %>
                        <tr>
                          <% (1..@location.column).each do |column| %>
                            <td>

                            </td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>





        </div>
      </div>
    </div>
  </div>
</section>

<%= content_for :specific_page_js do %>
  <script type="text/javascript">
    <%= render "location_form.js" %>
  </script>
<% end %>