config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root 'static_pages#index'
    resources :products
    resources :categories
    resources :tables
    resources :locations
    resources :reports, only: [:index, :show]
    resources :week_reports, only: [:index]
    resources :month_reports, only: [:index]
    resources :year_reports, only: [:index]
    namespace :ajax do
      resources :products_orders
      resources :orders_reports
      resources :week_reports
      resources :area_locations
    end
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  def index
    @order_of_day = Order
      .where("created_at between :begin_day and :end_day", begin_day: Time.current.beginning_of_day, end_day: Time.current.end_of_day)
      .where(order_status: 0)

    # tổng giá tiền
    @total_price = 0

    # tổng số sản phảm
    @total_products = 0

    @order_of_day.each do |order_of_day|
      total_price = order_of_day.product_orders.sum { |q| q.quantity  * q.product.price}
      @total_price += total_price

      total_products = order_of_day.product_orders.sum(:quantity)
      @total_products += total_products

    end

    # số order của ngày
    @total_order = @order_of_day.size

    # Thống kê 15 sản phẩm bán chạy
    @report_selling_product = []
    order_id_of_day = @order_of_day.pluck(:id)

    # Hiển thị tất cả các sản phẩm trong ngày

    # product_id_of_day = ProductOrder.where(order_id: order_id_of_day).pluck(:product_id).uniq
    # product_id_of_day.each do |product|
    #   name_product = Product.find_by_id(product).name
    #   quantity_product = ProductOrder.where(product_id: product, order_id: order_id_of_day).sum(:quantity)
    #   array_product = []
    #   array_product << name_product
    #   array_product << quantity_product
    #   @report_selling_product << array_product
    # end

    @report_selling_product = ProductOrder.joins(:product)
      .where(order_id: order_id_of_day)
      .select("sum(quantity) as total_quantity, product_id")
      .group(:product_id).order("total_quantity desc").first(15)
      .map{|po| [po.product.name, po.total_quantity]}

  end

  def create
  end

  def new
  end

  def destroy
  end

  def show
    @order_product_show = ProductOrder.includes(:product).where(order_id: params[:id])

    @order_show = Order.includes(:table).find_by_id params[:id]

    @show_total_price = @order_product_show.sum { |q| q.quantity  * q.product.price}

    @show_total_products = @order_product_show.sum(:quantity)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/_charts_info.html.erb
<div id="chartsproduct" style="min-width: 300px; height: 400px; margin: 0 auto" data-reportsproduct="<%= report_selling_product %>"></div>

app/views/admin/reports/_detail_info.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>
    <div class="info-box-content">
      <span class="info-box-text">Tổng Số Bàn</span>
      <span class="info-box-number"><%= total_order %> Bàn<small></small></span>
    </div>
  </div>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-red"><i class="fa fa-google-plus"></i></span>
    <div class="info-box-content">
      <span class="info-box-text">Tổng Tiền</span>
      <span class="info-box-number"><%= number_with_delimiter(total_price, locale: :en) %> VNĐ</span>
    </div>
  </div>
</div>
<div class="clearfix visible-sm-block"></div>
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-green"><i class="ion ion-ios-cart-outline"></i></span>
    <div class="info-box-content">
      <span class="info-box-text">Số Sản Phẩm</span>
      <span class="info-box-number"><%= total_products %></span>
    </div>
  </div>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>
    <div class="info-box-content">
      <span class="info-box-text">Số Người</span>
      <span class="info-box-number">Chưa Thống Kê</span>
    </div>
  </div>
</div>

app/views/admin/reports/_detail_info_show.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>
    <div class="info-box-content">
      <span class="info-box-text">Tên Bàn</span>
      <span class="info-box-number"><%= order_show.table.name %><small></small></span>
    </div>
  </div>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-red"><i class="fa fa-google-plus"></i></span>
    <div class="info-box-content">
      <span class="info-box-text">Tổng Tiền</span>
      <span class="info-box-number"><%= number_with_delimiter(show_total_price, locale: :en) %> VNĐ</span>
    </div>
  </div>
</div>
<div class="clearfix visible-sm-block"></div>
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-green"><i class="ion ion-ios-cart-outline"></i></span>
    <div class="info-box-content">
      <span class="info-box-text">Số Sản Phẩm</span>
      <span class="info-box-number"><%= show_total_products %></span>
    </div>
  </div>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
    <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>
    <div class="info-box-content">
      <span class="info-box-text">Số Người</span>
      <span class="info-box-number">Chưa Thống Kê</span>
    </div>
  </div>
</div>

app/views/admin/reports/_reports_form.js.erb
$(document).ready(function(){
  $(".btn-filter").on("click", function(){
    if($(".filtertable").css("display") == "none"){
      $(".filtertable").slideDown();
    }
    else {
      $(".filtertable").slideUp();
    }
  });

  $(".search-alert").on("click", function(){
    swal({
    title: "Đang Tìm Kiếm",
    timer: 2000,
    showConfirmButton: false,
    type: "success"
    });
  });


  $('#table_report_day').DataTable();

  $('#datetimepicker4').datetimepicker({
    locale: 'vi'
  });

  $(".btn-search-order").on("click", function(){
    var time = $(".datetime-report").val();
    var url_path = "<%= admin_ajax_orders_reports_path %>";
    $.ajax({
      type: "GET",
      url: url_path,
      dataType: "script",
      data: {
        time: time
      }
    });
  });
});


$(document).ready(function(){

  var data = $("#chartsproduct").data("reportsproduct");
  Highcharts.chart('chartsproduct', {
    chart: {
        type: 'column'
    },
    title: {
        text: '15 sản phẩm bán chạy nhất trong ngày'
    },
    xAxis: {
        type: 'category',
        labels: {
            rotation: -45,
            style: {
                fontSize: '13px',
                fontFamily: 'Verdana, sans-serif'
            }
        }
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Số Lượng Bán Ra'
        }
    },
    legend: {
        enabled: false
    },
    tooltip: {
        pointFormat: 'Bán được: <b>{point.y} Sản Phẩm</b>'
    },
    series: [{
        name: 'Population',
        data: data,
        dataLabels: {
            enabled: true,
            rotation: -90,
            color: '#FFFFFF',
            align: 'right',
            format: '{point.y} Sản Phẩm', // one decimal
            y: 10, // 10 pixels down from the top
            style: {
                fontSize: '13px',
                fontFamily: 'Verdana, sans-serif'
            }
        }
      }]
    });
});

app/views/admin/reports/_table_info.html.erb
<% if order_of_day.any? %>
  <table id="table_report_day" class="table table-hover table-striped">
    <thead class="thead-inverse">
      <th>Tên Bàn</th>
      <th>Tiền Thu Vào</th>
      <th>Thanh Toán Lúc</th>
      <th>Số Sản Phẩm</th>
      <th class="tac-vu">Tác Vụ</th>
    </thead>
    <tbody>
      <% order_of_day.each do |order| %>
        <tr>
          <td><%= order.table.name %></td>
          <td style=" color: red; " ><%= number_with_delimiter(order.product_orders.sum { |q| q.quantity * q.product.price }, locale: :en) %> VNĐ</td>
          <td><%= order.updated_at.strftime("%I:%M%p") %></td>
          <td><%= order.product_orders.sum(:quantity) %></td>
          <td class="tac-vu">
            <%= link_to admin_report_path(order.id), class: "button-show" do %>
                  <span class="button-inner">
                    <button class="btn button button-show-small">
                      <span class="text">Chi Tiết</span>
                    </button>
                  </span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3 class="text-center">Không có thông tin nào.</h3>
  <div class="col-xs-12 text-center margin-bottom-30">
    <%= link_to "Trở lại", admin_reports_path, class: "btn btn-default bg-red" %>
  </div>
<% end %>

app/views/admin/reports/_table_info_show.html.erb
<% if order_product_show.any? %>
  <table id="table_report_day" class="table table-hover table-striped">
    <thead class="thead-inverse">
      <th>Tên Sản Phẩm</th>
      <th>Đơn Giá</th>
      <th>Số Lượng</th>
      <th>Tổng Tiền</th>
    </thead>
    <tbody>
      <% order_product_show.each do |product_order| %>
        <tr>
          <td><%= product_order.product.name %></td>
          <td><%= product_order.product.price %> VNĐ</td>
          <td><%= product_order.quantity %></td>
          <td style=" color: red; " ><%= number_with_delimiter(product_order.quantity.to_i * product_order.product.price.to_i, locale: :en) %> VNĐ</td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3 class="text-center">Không có thông tin nào.</h3>
  <div class="col-xs-12 text-center margin-bottom-30">
    <%= link_to "Trở lại", admin_reports_path, class: "btn btn-default bg-red" %>
  </div>
<% end %>

app/views/admin/reports/create.html.erb
<h1>Admin::Reports#create</h1>
<p>Find me in app/views/admin/reports/create.html.erb</p>

app/views/admin/reports/destroy.html.erb
<h1>Admin::Reports#destroy</h1>
<p>Find me in app/views/admin/reports/destroy.html.erb</p>

app/views/admin/reports/index.html.erb
<section class="content-header menu-header-button">
  <%= link_to admin_root_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>


<section class="content">

  <div class="row">
    <div class="col-md-12">
      <div class="info-box">
        <span class="info-box-icon"><i class="ion ion-ios-heart-outline"></i></span>
        <div class="info-box-content">
          <div class="form-group">
            <div class="col-md-6">
              <label>Chọn ngày cần thống kê:</label>
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                <input type="text" id='datetimepicker4' class="form-control datetime-report" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">
              </div>
            </div>
            <div class="col-md-6" style=" margin-top: 25px ">
              <%= link_to "javascript:void(0);", class: "btn icon-btn btn-danger btn-search-order" do %>
                <span class="glyphicon btn-glyphicon glyphicon-search img-circle text-danger"></span>
                Xem Thông Tin
              <% end %>
            </div>
          </div>
          <div class="progress">
            <div class="progress-bar" style="width: 20%"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12" style="padding-left: 0px; padding-right: 0px;" id="reports-result-info">
      <%= render "admin/reports/detail_info", total_price: @total_price, total_order: @total_order, total_products: @total_products %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Sản Phẩm</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool btn-filter">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
        <div class="box-body table-responsive no-padding min-height-600">
          <div class="col-md-12">
            <div id="reports-result-table">
              <%= render "admin/reports/table_info", order_of_day: @order_of_day %>
            </div>
        </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Đồ Thị Sản Phẩm Trong Ngày</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool btn-filter">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
        <div class="box-body table-responsive no-padding min-height-600">
          <div id="charts-info">
            <%= render "admin/reports/charts_info", report_selling_product: @report_selling_product %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%= content_for :specific_page_js do %>
  <script type="text/javascript">
    <%= render "reports_form.js" %>
  </script>
<% end %>

app/views/admin/reports/new.html.erb
<h1>Admin::Reports#new</h1>
<p>Find me in app/views/admin/reports/new.html.erb</p>

app/views/admin/reports/show.html.erb
<section class="content-header menu-header-button">
  <%= link_to admin_root_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>


<section class="content">

  <div class="row">
    <div class="col-md-12" style="padding-left: 0px; padding-right: 0px;" id="reports-result-info">
      <%= render "admin/reports/detail_info_show", order_show: @order_show, show_total_price: @show_total_price, show_total_products: @show_total_products %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Sản Phẩm</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool btn-filter">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
        <div class="box-body table-responsive no-padding min-height-600">
          <div class="col-md-12">
            <div id="reports-result-table">
              <%= render "admin/reports/table_info_show", order_product_show: @order_product_show %>
            </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%= content_for :specific_page_js do %>
  <script type="text/javascript">
    <%= render "reports_form.js" %>
  </script>
<% end %>