config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root 'static_pages#index'
    resources :products
    resources :categories
    resources :tables
    resources :locations
    resources :reports, only: [:index, :show]
    resources :week_reports, only: [:index]
    resources :month_reports, only: [:index]
    resources :year_reports, only: [:index]
    namespace :ajax do
      resources :products_orders
      resources :orders_reports
      resources :week_reports
      resources :area_locations
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders, through: :product_orders
  has_many :product_orders, dependent: :destroy
  belongs_to :category

  validates :category, presence: true
  validates :name, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_category, only: %i(new edit create)
  before_action :load_product, only: %i(destroy edit show update)


  def index
    @search = Product.search params[:q]
    @search.sorts  = "created_at desc" if @search.sorts.empty?
    @products = @search.result.includes(:category).page(params[:page]).per_page 10
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = "Bạn đả tạo thành công"
      redirect_to admin_products_path
    else
      flash[:danger] = "Bạn đả tạo không thành công"
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @product.update_attributes product_params
      flash[:success] = "Chúc mừng bạn đả cập nhật thành công."
      redirect_to admin_products_path
    else
      flash[:danger] = "Xin lỗi ! Bạn đã cập nhật không thành công."
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = "Chúc mừng bạn đả xóa thành công."
    else
      flash[:danger] = "Xin lỗi ! Bạn đã xóa không thành công, xin thử lại."
    end
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit :code, :name, :description, :price, :unit, :category_id
  end

  def load_product
    @product = Product.find_by id: params[:id]
  end

  def load_category
    @categories = Category.all
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.code %></td>
  <td><%= product.name %></td>
  <td><%= product.category.name %></td>
  <td><%= product.description %></td>
  <td><%= product.price %></td>
  <td><%= product.unit %></td>
  <td class="tac-vu">
    <%= link_to admin_product_path(product), class: "button-show" do %>
          <span class="button-inner">
            <button class="btn button button-show-small">
              <span class="text">Chi Tiết</span>
            </button>
          </span>
    <% end %>
    <%= link_to edit_admin_product_path(product), class: "button-edit" do %>
          <span class="button-inner">
            <button class="btn button button-edit-small">
              <span class="text">Chỉnh Sửa</span>
            </button>
          </span>
    <% end %>
    <%= link_to admin_product_path(product),method: :delete,
      data: {confirm: "Bạn chắc chắn muốn xóa"}, class: "button-delete" do %>
          <span class="button-inner">
            <button class="btn button button-delete-small">
              <span class="text">Xóa</span>
            </button>
          </span>
    <% end %>
  </td>
</tr>

app/views/admin/products/_product_form.html.erb
<%= form_for [:admin, product], html: {class: "form-horizontal"} do |f| %>
<div class="error_messages_container">
  <%= render "admin/shared/error", object: f.object %>
</div>
  <div class="box-body">

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Mã Sản Phẩm</label>
      <div class="col-sm-8">
        <%= f.text_field :code, class: "form-control", placeholder: "Nhập Mã Sản Phẩm" %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Tên Sản Phẩm</label>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Nhập Tên Sản Phẩm" %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Loại Sản Phẩm</label>
      <div class="col-sm-8">
        <%= f.select :category_id,
          @categories.collect { |category| [ category.name, category.id ] },
          {include_blank: "Chọn loại sản phẩm"}, {class: "form-control "} %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Mô Tả</label>
      <div class="col-sm-8">
        <%= f.text_field :description, class: "form-control", placeholder: "Nhập Mô Tả" %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Giá Sản Phẩm</label>
      <div class="col-sm-8">
        <%= f.number_field :price, class: "form-control", placeholder: "Nhập Giá Sản Phẩm" %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Đơn Vị </label>
      <div class="col-sm-8">
        <%= f.text_field :unit, class: "form-control", placeholder: "Nhập Đơn Vị" %>
      </div>
      <div class="col-md-2">
      </div>
    </div>

  </div>
  <div class="box-footer">
    <%= link_to "Trở Về", admin_tables_path, class: "btn btn-default btn-warning" %>
    <% if product.persisted?%>
      <%= f.submit "Chỉnh Sửa", class: "btn btn-info pull-right load-alert" %>
    <% else %>
      <%= f.submit "Tạo Mới", class: "btn btn-info pull-right load-alert" %>
    <% end %>
  </div>
<% end %>

app/views/admin/products/_product_form_search.html.erb
<%= search_form_for [:admin, search] do |fs| %>
  <div class="box filtertable">
    <div class="box-header width-border">
      <h3 class="box-title">Tìm Sản Phẩm</h3>
    </div>
    <div class="box-body">
      <div class="col-md-12 form-group">
        <div class="col-md-6">
          <%= fs.search_field :name_cont, class: "form-control",
            placeholder: "Nhập Sản Phẩm" %>
        </div>
        <%= fs.submit "Tìm Kiếm", class: "btn btn-info col-md-1 search-alert" %>
        <%= link_to "Làm mới", admin_products_path, class: "btn btn-default col-md-1 margin-left-20 bg-green", data: {turbolinks: false} %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/products/_product_form_search.js.erb
$(document).ready(function(){
  $(".btn-filter").on("click", function(){
    if($(".filtertable").css("display") == "none"){
      $(".filtertable").slideDown();
    }
    else {
      $(".filtertable").slideUp();
    }
  });

  $(".search-alert").on("click", function(){
    swal({
    title: "Đang Tìm Kiếm",
    timer: 2000,
    showConfirmButton: false,
    type: "success"
    });
  });
});

app/views/admin/products/create.html.erb
<h1>Admin::Products#create</h1>
<p>Find me in app/views/admin/products/create.html.erb</p>

app/views/admin/products/edit.html.erb
<section class="content-header menu-header-button">
  <%= link_to new_admin_table_path, class: "btn icon-btn btn-danger" do %>
    <span class="glyphicon btn-glyphicon glyphicon-plus img-circle text-danger"></span>
    Thêm Mới
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t ".title" %></h3>
        </div>
        <%= render "product_form", product: @product %>
      </div>
    </div>
  </div>
</section>

app/views/admin/products/index.html.erb
<section class="content-header menu-header-button">
  <%= link_to new_admin_product_path, class: "btn icon-btn btn-danger" do %>
    <span class="glyphicon btn-glyphicon glyphicon-plus img-circle text-danger"></span>
    Thêm Mới
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>


<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Sản Phẩm</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool btn-filter">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
        <div class="box-body table-responsive no-padding min-height-600">
          <%= render "product_form_search", search: @search, form: @form %>
          <div class="notices_result">
            <% if @products.any? %>
              <table class="table table-hover table-striped">
                <thead class="thead-inverse">
                  <th><%= sort_link @search, :code, "Mã Sản Phẩm" %></th>
                  <th><%= sort_link @search, :name, "Tên Sản Phẩm" %></th>
                  <th><%= sort_link @search, :category_id, "Loại Sản Phẩm" %></th>
                  <th><%= sort_link @search, :description, "Mô Tả" %></th>
                  <th><%= sort_link @search, :price, "Giá" %></th>
                  <th><%= sort_link @search, :unit, "Đơn Vị" %></th>
                  <th class="tac-vu">Tác Vụ</th>
                </thead>
                <tbody>
                  <%= render @products %>
                </tbody>
              </table>
              <div class="pagination_center">
                <%= will_paginate @products %>
              </div>
            <% else %>
              <h3 class="text-center">Không có bàn nào.</h3>
              <div class="col-xs-12 text-center margin-bottom-30">
                <%= link_to "Trở lại", admin_products_path, class: "btn btn-default bg-red" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%= content_for :specific_page_js do %>
  <script type="text/javascript">
    <%= render "product_form_search.js" %>
  </script>
<% end %>

app/views/admin/products/new.html.erb
<section class="content-header menu-header-button">
  <%= link_to admin_tables_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Tạo Bàn Mới</h3>
        </div>
        <%= render "product_form", product: @product %>
      </div>
    </div>
  </div>
</section>

app/views/admin/products/show.html.erb
<section class="content-header menu-header-button">
  <%= link_to new_admin_product_path, class: "btn icon-btn btn-danger" do %>
    <span class="glyphicon btn-glyphicon glyphicon-plus img-circle text-danger"></span>
    Thêm Mới
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-warning" do %>
    <span class="glyphicon btn-glyphicon glyphicon-circle-arrow-left img-circle text-warning"></span>
    Trở Về
  <% end %>

  <%= link_to admin_root_path, class: "btn icon-btn btn-primary" do %>
    <span class="glyphicon btn-glyphicon glyphicon-share img-circle text-primary"></span>
    Trang Quản Lý
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-success" do %>
    <span class="glyphicon btn-glyphicon glyphicon-open-file img-circle text-success"></span>
    Nhập Từ Excel
  <% end %>

  <%= link_to "", class: "btn icon-btn btn-info" do %>
    <span class="glyphicon btn-glyphicon glyphicon-paste img-circle text-info"></span>
    Xuất Excel
  <% end %>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-default box-solid">
        <div class="box-header width-border">
          <h3 class="box-title">Sản Phẩm</h3>
          <div class="box-tools pull-right"></div>
        </div>
        <div class="box-body body-notice-box">
          <div class="col-md-12">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label"><h3>Mã Sản Phẩm :</h3></label>
              <div class="col-sm-10">
                <h3><%= @product.code %></h3>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label"><h3>Tên Sản Phẩm :</h3></label>
              <div class="col-sm-10">
                <h3><%= @product.name %></h3>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label"><h3>Thể Loại :</h3></label>
              <div class="col-sm-10">
                <h3><%= @product.category.name %></h3>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label"><h3>Mô Tả :</h3></label>
              <div class="col-sm-10">
                <h3><%= @product.description %></h3>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label"><h3>Giá :</h3></label>
              <div class="col-sm-10">
                <h3><%= @product.price %></h3>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label"><h3>Đơn Vị :</h3></label>
              <div class="col-sm-10">
                <h3><%= @product.unit %></h3>
              </div>
            </div>
          </div>

        </div>
        <div class="box-footer">
          <div class="col-md-12">
            <%= link_to t(".back"), admin_products_path, class: "btn btn-info pull-right" %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 text-center"></div>
  </div>
</section>